/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjetoSemana8;

import javax.swing.JOptionPane;

/**
 *
 * @author Jardel
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painel = new javax.swing.JTextField();
        botao9 = new javax.swing.JButton();
        botao1 = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao0 = new javax.swing.JButton();
        botaoAdicao = new javax.swing.JButton();
        botaoSubtracao = new javax.swing.JButton();
        botaoMultiplicacao = new javax.swing.JButton();
        botaoDivisao = new javax.swing.JButton();
        botaoIgual = new javax.swing.JButton();
        botaoVirgula = new javax.swing.JButton();
        botaoApagar = new javax.swing.JButton();
        botaoLimpaTela = new javax.swing.JButton();
        botaoQ = new javax.swing.JButton();
        botaoSinal = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora ");
        setResizable(false);

        painel.setEditable(false);
        painel.setBackground(java.awt.Color.white);
        painel.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        painel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        painel.setText("0");
        painel.setToolTipText("");
        painel.setName("campoResultado"); // NOI18N
        painel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                painelActionPerformed(evt);
            }
        });

        botao9.setText("9");
        botao9.setName("botao9"); // NOI18N
        botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao9ActionPerformed(evt);
            }
        });

        botao1.setText("1");
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });

        botao6.setText("6");
        botao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao6ActionPerformed(evt);
            }
        });

        botao2.setText("2");
        botao2.setMaximumSize(new java.awt.Dimension(41, 23));
        botao2.setMinimumSize(new java.awt.Dimension(41, 23));
        botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao2ActionPerformed(evt);
            }
        });

        botao3.setText("3");
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });

        botao7.setText("7");
        botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao7ActionPerformed(evt);
            }
        });

        botao8.setText("8");
        botao8.setMaximumSize(new java.awt.Dimension(41, 23));
        botao8.setMinimumSize(new java.awt.Dimension(41, 23));
        botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao8ActionPerformed(evt);
            }
        });

        botao4.setText("4");
        botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao4ActionPerformed(evt);
            }
        });

        botao5.setText("5");
        botao5.setMaximumSize(new java.awt.Dimension(41, 23));
        botao5.setMinimumSize(new java.awt.Dimension(41, 23));
        botao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao5ActionPerformed(evt);
            }
        });

        botao0.setText("0");
        botao0.setMaximumSize(new java.awt.Dimension(41, 23));
        botao0.setMinimumSize(new java.awt.Dimension(41, 23));
        botao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao0ActionPerformed(evt);
            }
        });

        botaoAdicao.setText("+");
        botaoAdicao.setName("botao9"); // NOI18N
        botaoAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicaoActionPerformed(evt);
            }
        });

        botaoSubtracao.setText("-");
        botaoSubtracao.setName("botao9"); // NOI18N
        botaoSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSubtracaoActionPerformed(evt);
            }
        });

        botaoMultiplicacao.setText("X");
        botaoMultiplicacao.setName("botao9"); // NOI18N
        botaoMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMultiplicacaoActionPerformed(evt);
            }
        });

        botaoDivisao.setText("÷");
        botaoDivisao.setName("botao9"); // NOI18N
        botaoDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDivisaoActionPerformed(evt);
            }
        });

        botaoIgual.setText("=");
        botaoIgual.setName("botao9"); // NOI18N
        botaoIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIgualActionPerformed(evt);
            }
        });

        botaoVirgula.setText(",");
        botaoVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVirgulaActionPerformed(evt);
            }
        });

        botaoApagar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jardel\\Downloads\\icons8-backspace-50 (3).png")); // NOI18N
        botaoApagar.setName("botao9"); // NOI18N
        botaoApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoApagarActionPerformed(evt);
            }
        });

        botaoLimpaTela.setText("C");
        botaoLimpaTela.setMaximumSize(new java.awt.Dimension(41, 23));
        botaoLimpaTela.setMinimumSize(new java.awt.Dimension(41, 23));
        botaoLimpaTela.setName("botao9"); // NOI18N
        botaoLimpaTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimpaTelaActionPerformed(evt);
            }
        });

        botaoQ.setText("x²");
        botaoQ.setName("botao9"); // NOI18N
        botaoQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoQActionPerformed(evt);
            }
        });

        botaoSinal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botaoSinal.setText("+/-");
        botaoSinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSinalActionPerformed(evt);
            }
        });

        labelResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botaoQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botao4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoSinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botao1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botao7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botao0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoVirgula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botaoLimpaTela, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(botao5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botao8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botao6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botao9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoApagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoDivisao)
                            .addComponent(botaoIgual)
                            .addComponent(botaoAdicao)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botao0, botao1, botao2, botao3, botao4, botao5, botao6, botao7, botao8, botao9, botaoAdicao, botaoApagar, botaoDivisao, botaoIgual, botaoLimpaTela, botaoMultiplicacao, botaoQ, botaoSinal, botaoSubtracao, botaoVirgula});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoLimpaTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoQ))
                    .addComponent(botaoAdicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao7)
                    .addComponent(botao8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSubtracao)
                    .addComponent(botao9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao4)
                    .addComponent(botao5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao6)
                    .addComponent(botaoMultiplicacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao1)
                    .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao3)
                    .addComponent(botaoDivisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoIgual)
                    .addComponent(botaoVirgula)
                    .addComponent(botaoSinal))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botao0, botao1, botao2, botao3, botao4, botao5, botao6, botao7, botao8, botao9, botaoAdicao, botaoApagar, botaoDivisao, botaoIgual, botaoLimpaTela, botaoMultiplicacao, botaoQ, botaoSinal, botaoSubtracao, botaoVirgula});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void painelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_painelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_painelActionPerformed

    private void botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2ActionPerformed
        this.verificaPainel();
        if(labelResultado.getText().contains("=")){
           labelResultado.setText("2");
           painel.setText("2");
       }else{
           if(Double.parseDouble(painel.getText())==0){
           painel.setText("2");
            }else{
                painel.setText(painel.getText()+"2");
           }
       }
    }//GEN-LAST:event_botao2ActionPerformed

    private void botao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao0ActionPerformed
        this.verificaPainel();
        if(!painel.getText().equalsIgnoreCase("0")){
            painel.setText(painel.getText()+"0");
        }
        if(labelResultado.getText().contains("=")){
           labelResultado.setText("0");
           painel.setText("0");
        }
    }//GEN-LAST:event_botao0ActionPerformed

    private void botaoDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDivisaoActionPerformed
        this.operacao="/";
        labelResultado.setText(painel.getText()+"÷");
if(painel.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Informe um número antes de clicar na operação.");
        }else{
            this.numero1=Double.parseDouble(painel.getText());
            if(this.numero1>0){
            this.numero2=Double.parseDouble(painel.getText());
        }
        }
        painel.setText("0");
    }//GEN-LAST:event_botaoDivisaoActionPerformed

    private void botaoIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIgualActionPerformed
this.numero2=Double.parseDouble(painel.getText());
switch(operacao){
    case "+":
        if(!labelResultado.getText().contains("=")){
            labelResultado.setText(labelResultado.getText()+painel.getText()+"=");
        }
        this.painel.setText(""+(this.numero1+this.numero2));
      break;
    case "-":
        if(!labelResultado.getText().contains("=")){
            labelResultado.setText(labelResultado.getText()+painel.getText()+"=");
        }
        this.painel.setText(""+(this.numero1-this.numero2));
        break;
    case "/":
        if(!labelResultado.getText().contains("=")){
            labelResultado.setText(labelResultado.getText()+painel.getText()+"=");
        }
        this.painel.setText(""+(this.numero1/this.numero2));
        break;
    case "*":
        if(!labelResultado.getText().contains("=")){
            labelResultado.setText(labelResultado.getText()+painel.getText()+"=");
        }
        this.painel.setText(""+(this.numero1*this.numero2));
        break;
}

    }//GEN-LAST:event_botaoIgualActionPerformed

    private void botaoVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVirgulaActionPerformed
       if(!painel.getText().contains(".")){
           painel.setText(painel.getText()+".");
       }
    }//GEN-LAST:event_botaoVirgulaActionPerformed

    private void botaoSinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSinalActionPerformed
       if(!painel.getText().contains("-")){
           String aux = painel.getText();
           painel.setText("-"+aux);
       }else{
           painel.setText(painel.getText().substring(1, painel.getText().length()));
       }
    }//GEN-LAST:event_botaoSinalActionPerformed

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        this.verificaPainel();
        if(labelResultado.getText().contains("=")){
           labelResultado.setText("1");
           painel.setText("1");
       }else{
           if(Double.parseDouble(painel.getText())==0){
           painel.setText("1");
            }else{
                painel.setText(painel.getText()+"1");
           }
       }
    }//GEN-LAST:event_botao1ActionPerformed

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed
        this.verificaPainel();
        if(labelResultado.getText().contains("=")){
           labelResultado.setText("3");
           painel.setText("3");
       }else{
           if(Double.parseDouble(painel.getText())==0){
           painel.setText("3");
            }else{
                painel.setText(painel.getText()+"3");
           }
       }
    }//GEN-LAST:event_botao3ActionPerformed

    private void botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao4ActionPerformed
        this.verificaPainel();
        if(labelResultado.getText().contains("=")){
           labelResultado.setText("4");
           painel.setText("4");
       }else{
           if(Double.parseDouble(painel.getText())==0){
           painel.setText("4");
            }else{
                painel.setText(painel.getText()+"4");
           }
       }
    }//GEN-LAST:event_botao4ActionPerformed

    private void botao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao5ActionPerformed
       this.verificaPainel();
        if(labelResultado.getText().contains("=")){
           labelResultado.setText("5");
           painel.setText("5");
       }else{
           if(Double.parseDouble(painel.getText())==0){
           painel.setText("5");
            }else{
                painel.setText(painel.getText()+"5");
           }
       }
    }//GEN-LAST:event_botao5ActionPerformed

    private void botao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao6ActionPerformed
        this.verificaPainel();
        if(labelResultado.getText().contains("=")){
           labelResultado.setText("6");
           painel.setText("6");
       }else{
           if(Double.parseDouble(painel.getText())==0){
           painel.setText("6");
            }else{
                painel.setText(painel.getText()+"6");
           }
       }
    }//GEN-LAST:event_botao6ActionPerformed

    private void botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao7ActionPerformed
       this.verificaPainel();
        if(labelResultado.getText().contains("=")){
           labelResultado.setText("7");
           painel.setText("7");
       }else{
           if(Double.parseDouble(painel.getText())==0){
           painel.setText("7");
            }else{
                painel.setText(painel.getText()+"7");
           }
       }
    }//GEN-LAST:event_botao7ActionPerformed

    private void botao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao8ActionPerformed
        this.verificaPainel();
        if(labelResultado.getText().contains("=")){
           labelResultado.setText("8");
           painel.setText("8");
       }else{
           if(Double.parseDouble(painel.getText())==0){
           painel.setText("8");
            }else{
                painel.setText(painel.getText()+"8");
           }
       }
    }//GEN-LAST:event_botao8ActionPerformed

    private void botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao9ActionPerformed
       if(labelResultado.getText().contains("=")){
           labelResultado.setText("9");
           painel.setText("9");
       }else{
           if(Double.parseDouble(painel.getText())==0){
           painel.setText("9");
            }else{
                painel.setText(painel.getText()+"9");
           }
       }
    }//GEN-LAST:event_botao9ActionPerformed

    private void botaoLimpaTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimpaTelaActionPerformed
        painel.setText("0");
        labelResultado.setText("");
        numero1=0;
        numero2=0;
    }//GEN-LAST:event_botaoLimpaTelaActionPerformed

    private void botaoSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSubtracaoActionPerformed
        this.operacao="-";
        labelResultado.setText(painel.getText()+"-");
if(painel.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Informe um número antes de clicar na operação.");
        }else{
            this.numero1=Double.parseDouble(painel.getText());
            if(this.numero1>0){
            this.numero2=Double.parseDouble(painel.getText());
        }
        }
        painel.setText("0");
    }//GEN-LAST:event_botaoSubtracaoActionPerformed

    private void botaoAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicaoActionPerformed
this.operacao= "+";
labelResultado.setText(painel.getText()+"+");
if(painel.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Informe um número antes de clicar na operação.");
        }else{
            this.numero1=Double.parseDouble(painel.getText());
            if(this.numero1>0){
            this.numero2=Double.parseDouble(painel.getText());
        }
        }
        painel.setText("0");
       
    }//GEN-LAST:event_botaoAdicaoActionPerformed
private void verificaPainel(){
    if(labelResultado.getText().contains("sqr")){
        painel.setText("0");
        labelResultado.setText("");
    }
}
    private void botaoApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoApagarActionPerformed
        painel.setText(painel.getText().substring(0, painel.getText().length()-1));
    }//GEN-LAST:event_botaoApagarActionPerformed

    private void botaoMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMultiplicacaoActionPerformed
        this.operacao="*";
        labelResultado.setText(painel.getText()+"x");
if(painel.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Informe um número antes de clicar na operação.");
        }else{
            this.numero1=Double.parseDouble(painel.getText());
            if(this.numero1>0){
            this.numero2=Double.parseDouble(painel.getText());
        }
        }
        painel.setText("0");
    }//GEN-LAST:event_botaoMultiplicacaoActionPerformed

    private void botaoQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoQActionPerformed
        numero1=Double.parseDouble(painel.getText());
        painel.setText(""+numero1*numero1);
        labelResultado.setText("sqr("+numero1+")");
    }//GEN-LAST:event_botaoQActionPerformed
double numero1=0;
double numero2=0;
String operacao;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao0;
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JButton botaoAdicao;
    private javax.swing.JButton botaoApagar;
    private javax.swing.JButton botaoDivisao;
    private javax.swing.JButton botaoIgual;
    private javax.swing.JButton botaoLimpaTela;
    private javax.swing.JButton botaoMultiplicacao;
    private javax.swing.JButton botaoQ;
    private javax.swing.JButton botaoSinal;
    private javax.swing.JButton botaoSubtracao;
    private javax.swing.JButton botaoVirgula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JTextField painel;
    // End of variables declaration//GEN-END:variables
}
